#ifndef lpc_drivers_h
#define lpc_drivers_h

#include "../LPC845.h"
#include "../LPC845_AL.h"

#include "../drivers/fsl_acomp.h"
#include "../drivers/fsl_adc.h"
#include "../drivers/fsl_capt.h"
#include "../drivers/fsl_clock.h"
#include "../drivers/fsl_common.h"
#include "../drivers/fsl_crc.h"
#include "../drivers/fsl_ctimer.h"
#include "../drivers/fsl_dac.h"
#include "../drivers/fsl_dma.h"
#include "../drivers/fsl_gpio.h"
#include "../drivers/fsl_i2c.h"
#include "../drivers/fsl_iap.h"
#include "../drivers/fsl_inputmux.h"
#include "../drivers/fsl_inputmux_connections.h"
#include "../drivers/fsl_iocon.h"
#include "../drivers/fsl_mrt.h"
#include "../drivers/fsl_pint.h"
#include "../drivers/fsl_power.h"
#include "../drivers/fsl_reset.h"
#include "../drivers/fsl_sctimer.h"
#include "../drivers/fsl_spi.h"
#include "../drivers/fsl_swm.h"
#include "../drivers/fsl_swm_connections.h"
#include "../drivers/fsl_syscon.h"
#include "../drivers/fsl_syscon_connections.h"
#include "../drivers/fsl_usart.h"
#include "../drivers/fsl_wkt.h"
#include "../drivers/fsl_wwdt.h"

#endif